# Generated by Django 6.0.1 on 2026-01-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_description_product_sku'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='categories_supplies',
            field=models.ManyToManyField(related_name='suppliers', to='inventory.category'),
        ),
    ]
