from django.urls import path
from . import views

urlpatterns = [
    path('products/', views.product_list, name='product_list'),
    path('products/add/', views.add_product, name='add_product'),
    path("products/dashboard/", views.product_dashboard, name="product_dashboard"),
    path('product/update/<int:pk>/', views.update_product, name='update_product'),
    path('product/delete/<int:pk>/', views.delete_product, name='delete_product'),
    path('product/export/csv', views.export_product_csv, name="export_product_csv"),
    path('product/export/excel', views.export_product_excel,
         name="export_product_excel"),
    path('product/export/pdf', views.export_product_pdf, name="export_product_pdf"),
    path('categories/', views.category_list, name='category_list'),
    path('categories/<int:category_id>/',
         views.category_products, name='category_products'),
    path('categories/add/', views.add_category, name='add_category'),
    path('categories/update/<int:pk>/',
         views.update_category, name='update_category'),
    path('categories/delete/<int:pk>/',
         views.delete_category, name='delete_category'),
    path('categories/dashboard/', views.category_dashboard,
         name='category_dashboard'),
    path('category/without-products/', views.category_without_products,
         name="category_without_products"),
    path('category/with-products/', views.category_with_products,
         name="category_with_products"),
    path('category/export/csv', views.export_category_csv,
         name="export_category_csv"),
    path('category/export/excel', views.export_category_excel,
         name="export_category_excel"),
    path('category/export/pdf', views.export_category_pdf,
         name="export_category_pdf"),
    path('reports/dashboard/', views.report_dashboard,
         name='report_dashboard'),
    path('stock/dashboard/', views.stock_dashboard,
         name='stock_dashboard'),
    path('stock/in/', views.stock_in, name='stock_in_section'),
    path('stock/in/<int:product_id>', views.stock_in, name='stock_in'),
    path('stock/out/', views.stock_out, name='stock_out'),
    path('in-stock/', views.in_stock_products, name='in_stock'),
    path('low-stock/', views.low_stock_products, name='low_stock'),
    path('out-stock/', views.out_stock_products, name='out_stock'),
    path('stock/history/', views.stock_history, name='stock_history'),
    path('stock/export/instock/csv', views.export_instock_csv,
         name="export_instock_csv"),
    path('stock/export/instock/excel', views.export_instock_excel,
         name="export_instock_excel"),
    path('stock/export/instock/pdf', views.export_instock_pdf,
         name="export_instock_pdf"),
    path('stock/export/lowstock/csv', views.export_lowstock_csv,
         name="export_lowstock_csv"),
    path('stock/export/lowstock/excel', views.export_lowstock_excel,
         name="export_lowstock_excel"),
    path('stock/export/lowstock/pdf', views.export_lowstock_pdf,
         name="export_lowstock_pdf"),
    path('stock/export/outstock/csv', views.export_outstock_csv,
         name="export_outstock_csv"),
    path('stock/export/outstock/excel', views.export_outstock_excel,
         name="export_outstock_excel"),
    path('stock/export/outstock/pdf', views.export_outstock_pdf,
         name="export_outstock_pdf"),
]
