# Generated by Django 6.0.1 on 2026-02-03 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_remove_purchaseitem_purchase_and_more'),
        ('suppliers', '0003_supplier_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier'),
        ),
    ]
