# Generated by Django 6.0.1 on 2026-02-03 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_purchaserequest_supplier'),
        ('suppliers', '0003_supplier_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier'),
        ),
    ]
