# Generated by Django 6.0.1 on 2026-02-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_purchaseorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='description',
            field=models.CharField(default='None', max_length=500),
        ),
    ]
