# Generated by Django 6.0.1 on 2026-02-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0007_purchaserequest_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('shipped', 'Shipped'), ('In transit', 'In Transit'), ('delivered', 'Delivered'), ('delayed', 'Delayed')], default='ordered', max_length=20),
        ),
    ]
