# Generated by Django 6.0.1 on 2026-02-17 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0009_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('ordered', 'Ordered'), ('shipped', 'Shipped'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('delayed', 'Delayed')], default='draft', max_length=20),
        ),
    ]
