# Generated by Django 6.0.1 on 2026-02-17 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0010_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='warehouse_address',
            field=models.TextField(default='Ahmedabad , Gujarat'),
        ),
    ]
