# Generated by Django 6.0.1 on 2026-03-03 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0011_purchaseorder_warehouse_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='warehouse_address',
            field=models.TextField(default='Ahmedabad, Gujarat'),
        ),
    ]
