# Generated by Django 6.0.1 on 2026-01-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default=1234, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
