# Generated by Django 6.0.1 on 2026-02-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_stocklog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
