# Generated by Django 6.0.1 on 2026-02-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_product_warranty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='warranty',
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_months',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
