# Generated by Django 6.0.1 on 2026-02-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_remove_product_warranty_product_warranty_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='warranty_months',
            field=models.PositiveIntegerField(default=0, help_text='Warranty period in months'),
        ),
    ]
