# Generated by Django 6.0.1 on 2026-01-26 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Product taken', 'Product taken'), ('Cancelled', 'Cancelled')], max_length=20),
        ),
    ]
