# Generated by Django 6.0.1 on 2026-02-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Smart Inventory System', max_length=200)),
                ('company_address', models.TextField(default='Surat, Gujarat, India')),
                ('company_phone', models.CharField(default='+91 9876543210', max_length=20)),
                ('company_email', models.EmailField(default='support@smartinventory.com', max_length=254)),
                ('currency_symbol', models.CharField(default='₹', max_length=5)),
                ('low_stock_threshold', models.PositiveIntegerField(default=5)),
                ('default_warranty_months', models.PositiveIntegerField(default=12)),
                ('items_per_page', models.PositiveIntegerField(default=10)),
                ('notification_retention_days', models.PositiveIntegerField(default=15)),
                ('enable_product_notifications', models.BooleanField(default=True)),
                ('enable_stock_notifications', models.BooleanField(default=True)),
                ('enable_order_notifications', models.BooleanField(default=True)),
                ('enable_supplier_notifications', models.BooleanField(default=True)),
                ('enable_category_notifications', models.BooleanField(default=True)),
                ('enable_purchase_notifications', models.BooleanField(default=True)),
                ('default_warehouse_address', models.TextField(default='Ahmedabad, Gujarat')),
                ('default_supplier_lead_days', models.PositiveIntegerField(default=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
