# Generated by Django 6.0.1 on 2026-02-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_options_remove_notification_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('product', 'Product Activity'), ('category', 'Category Activity'), ('supplier', 'Supplier Activity'), ('stock', 'Stock Activity'), ('purchase', 'Purchase Activity')], max_length=20, null=True),
        ),
    ]
