# Generated by Django 6.0.1 on 2026-02-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('product', 'Product Activity'), ('category', 'Category Activity'), ('supplier', 'Supplier Activity'), ('stock', 'Stock Activity'), ('purchase', 'Purchase Activity'), ('order', 'Order Activity')], max_length=20, null=True),
        ),
    ]
