# Generated by Django 6.0.1 on 2026-02-13 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='link',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='role_target',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user_target',
        ),
        migrations.AddField(
            model_name='notification',
            name='allowed_roles',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='notification',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('product', 'Product Activity'), ('category', 'Category Activity'), ('supplier', 'Supplier Activity'), ('stock', 'Stock Activity'), ('purchase', 'Purchase Activity'), ('order', 'Order Activity')], default='system', max_length=20),
            preserve_default=False,
        ),
    ]
