# Generated by Django 6.0.1 on 2026-02-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_alter_notification_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='allowed_roles',
            field=models.CharField(default=list),
        ),
    ]
