# Generated by Django 6.0.1 on 2026-02-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_alter_notification_allowed_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='allowed_roles',
            field=models.CharField(max_length=100),
        ),
    ]
